# ===================================================================
#                   General configuration
# ===================================================================

logging:
  level:
    dk.sunepoulsen.tes.springboot: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

requests:
  logging:
    include-query-string: true
    include-headers: true
    include-payload: true
    payload-max-size: 10000
    message-prefix: 'REQUEST DATA: '

# ===================================================================
#                   Swagger configuration
# ===================================================================

springdoc:
  show-actuator: true
  default-produces-media-type: 'application/json'
  model-converters:
    pageable-converter:
      enabled: true

# ===================================================================
#                   Spring configuration
# ===================================================================

spring:
  liquibase:
    change-log: 'classpath:/db/changelog/changelog.xml'

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
